export const migration = [
  { source: "overview", destination: "/ and /architecture/" },
  { source: "build", destination: "/guide/#start" },
  { source: "firmware", destination: "/status/#firmware" },
  { source: "bitboards", destination: "/architecture/#board" },
  { source: "position", destination: "/architecture/#board" },
  { source: "move_encoding", destination: "/architecture/#moves" },
  { source: "movegen", destination: "/architecture/#moves" },
  { source: "makemove", destination: "/architecture/#moves" },
  { source: "zobrist", destination: "/architecture/#board" },
  { source: "perft", destination: "/guide/#test" },
  { source: "search", destination: "/architecture/#search" },
  { source: "quiescence", destination: "/architecture/#search" },
  { source: "eval_classic", destination: "/architecture/#search" },
  { source: "nnue_inference", destination: "/architecture/#nnue" },
  { source: "factorized_halfkp", destination: "/architecture/#nnue" },
  { source: "nnue_profiles", destination: "/results/" },
  { source: "train_model", destination: "/guide/#train" },
  { source: "training_parameters", destination: "/guide/#parameters" },
  { source: "training_pipeline", destination: "/guide/#data" },
  { source: "testing", destination: "/guide/#test" },
  { source: "benchmarks", destination: "/results/#host" },
] as const;
